version: "2"
services:
  proxy:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    networks:
      - web-server
    volumes:
      - certs:/etc/letsencrypt/
      # - letsencrypt_www:/var/www/letsencrypt/
      # - "./Jsonize-Web:/usr/share/nginx/html"
      - "./nginx-conf/:/etc/nginx/"
    restart: always
  # letsencrypt:
  #   image: quay.io/letsencrypt/letsencrypt:latest
  #   ports:
  #     - 3001:80
  #   networks:
  #     - web-server
  #   volumes:
  #     - letsencrypt_www:/var/www/letsencrypt/
  #     - certs:/etc/letsencrypt
  #   depends_on:
  #     - proxy
  node:
    # image: node:stable
    build:
      context: .
      dockerfile: Depthcharge.Render/Dockerfile
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - proxy
    volumes:
      - "./Depthcarge.Render/:/usr/local/Depthcharge.Render/"
    networks:
      - web-server
  dotnet-site:
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Jsonize-Web/Dockerfile
    # image: microsoft/dotnet:latest
    command: dotnet run
    environment:
      - DepthchargeRenderUrl="http://localhost:3000/api/render"
    depends_on:
      - proxy
    volumes:
      - "./Jsonize-Web/:/usr/local/Jsonize-Web"
    networks:
      - web-server
volumes:
  certs: ~
  letsencrypt_www: ~
networks:
  web-server:

