version: "2"
services:
  proxy:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    networks:
      - web-server
    volumes:
      - certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/letsencrypt
      - "./JackWFinlay.github.io:/usr/share/nginx/html"
      - "./nginx-conf:/etc/nginx/conf.d/"
    restart: always
  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    ports:
      - 3001:80
    networks:
      - web-server
    volumes:
      - certs:/etc/letsencrypt
    depends_on:
      - proxy
  node:
    image: node
    ports:
      - 3000:3000
    depends_on:
      - proxy
    volumes:
      - "./Blog-Engine:/usr/local/blog-engine"
volumes:
  certs: ~
  letsencrypt_www: ~
networks:
  web-server:

